// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extensibility.VisualStudio.Restart
{
    static class Vsix
    {
        public const string Id = "11FC685D-F80B-4265-BCD3-2DDBDED2EA33";
        public const string Name = "Restart Visual Studio";
        public const string Description = @"This extension simplify restarting visual studio with elevated rights reopening the current project or solution.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mario Hsiao";
        public const string Tags = "Restart, Restart as Administrator, Visual Studio 2015, Visual Studio 15";
    }
}
